apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: learnk8s/knote-java:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo.dbs:27017/dev
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: knote
  namespace: apps
spec:
  selector:
    app: knote
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

