IMAGE_NAME = "bento/ubuntu-22.04"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
      
    config.vm.define "master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "public_network", bridge: "wlo1", ip: "192.168.1.10"
        master.vm.hostname = "master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/master.yml"
            ansible.extra_vars = {
                node_ip: "192.168.1.10",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "worker0#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "public_network", bridge: "wlo1", ip: "192.168.1.#{i + 10}"
            node.vm.hostname = "worker0#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/worker.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.1.#{i + 10}",
                }
            end
        end
    end
end
