apiVersion: v1
kind: Service
metadata:
  name: renderer
  namespace: default
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: grafana-image-renderer
  type: ClusterIP
