apiVersion: v1
kind: Namespace
metadata:
  name: default

apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-service-account 
  namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-service-account-token
  namespace: default 
  annotations:
    kubernetes.io/service-account.name: "grafana-service-account"
type: kubernetes.io/service-account-token
