apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana--cluster-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: grafana-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: grafana-cluster-role
  apiGroup: rbac.authorization.k8s.io
